spring:
  datasource:
#    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/ToutEstAfricain}
#    username: ${JDBC_DATABASE_USERNAME:postgres}
#    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}

    url: ${JDBC_DATABASE_URL:jdbc:postgresql://postgresql-netra.alwaysdata.net:5432/netra_tea}
    username: ${JDBC_DATABASE_USERNAME:netra}
    password: ${JDBC_DATABASE_PASSWORD:Passer123}

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

#Log level configuration
logging:
  level:
    root: error
    com:
      testspringboot: info
    org:
      springframework:
        boot:
          autoconfigure:
            h2: info
          web:
            embedded:
              tomcat: info

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      UserUuidUnique: USER_UUID_UNIQUE
      UserEmailUnique: USER_EMAIL_UNIQUE
      RoleRoleNameUnique: ROLE_ROLE_NAME_UNIQUE
      OrderUuidUnique: ORDER_UUID_UNIQUE
springdoc:
  pathsToMatch: /api/**
